### ISSUE TITLE
Missing TopCover with holes for the optional picatinny

### ISSUE THREAD

**Issue by SleepLessThan3** [Sillybutts/SLAB#1]
![image](https://user-images.githubusercontent.com/61036902/230508592-b87478d3-49db-4423-9de0-6881201b2f34.png)

**Comment by Sillybutts** [comment]
Whoops, forgot to upload the new file apparently. Fixed now, thanks for catching that.

**Comment by SleepLessThan3** [comment]
The part from the f3d has 3mm holes for the picatinny instead of 2.4mm
