### ISSUE TITLE
The same one from yesterday

### ISSUE THREAD

**Issue by SleepLessThan3** [Sillybutts/SLAB#2]
https://github.com/Sillybutts/SLAB/issues/1
the holes are 3mm instead of 2.4mm, the screws spin freely. Also need to update the corresponding stl since I just ripped it from the f3d.

**Comment by SleepLessThan3** [comment]
![Capture](https://user-images.githubusercontent.com/61036902/230810608-121384d7-7b8e-4b4e-8df0-e81a9b7d859e.JPG)

**Comment by Sillybutts** [comment]
Fixed!
