### ISSUE TITLE
Adjust metric side panel A to not require support

### ISSUE THREAD

**Issue by joshdev-de** [Sillybutts/SLAB#3]
The METRIC_SidePanel_R.stl needs support for the hole marked in the pictures. Maybe something like this is an option?

https://www.youtube.com/watch?v=W8FbHTcB05w
The resulting little dent in the hole could maybe be countered with a whasher that has "the missing part" from the hole?

![grafik](https://user-images.githubusercontent.com/50580250/235374549-ddb635a3-14c5-4e9d-9289-f7f4c3c310e9.png)
![grafik](https://user-images.githubusercontent.com/50580250/235374562-d6ce57d0-69b0-4943-8151-a5b91ee613c9.png)

**Comment by Sillybutts** [comment]
I have updated the part to have a chamfered hole, no supports are necessary. The original imperial spec part already has a chamfered hole.
